### ISSUE TITLE
Integration does not work after Homeassistant Upgrade to 2022.3.4 (March 11) 

### ISSUE THREAD

**Issue by rosch99** [JoDehli/PyLoxone#110]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
MiniServeer Gen1

**Which software version does your loxone use?**
12.2.12.1

**How did you install HomeAssistant? Over Hassio oder manual install?**
Docker container on RPi

**Which Version do you use of HomeAssistant?**
2022.3.4

**Describe the bug**
After upgrading to 2022.3.4 pyloxone intergration does not start.
It used to work without problems before.

**Paste the error log with the following settings:**
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/loxone/api.py:77
Integration: PyLoxone (documentation, issues)
First occurred: 21:24:00 (2 occurrences)
Last logged: 21:39:03

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests_async/api.py", line 6, in request
    return await session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/sessions.py", line 79, in request
    resp = await self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/sessions.py", line 136, in send
    r = await adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/adapters.py", line 42, in send
    ssl = httpcore.SSLConfig(cert=cert, verify=verify)
**AttributeError: module 'httpcore' has no attribute 'SSLConfig'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 141, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 110, in async_setup
    request_code = await self.lox_config.getJson()
  File "/config/custom_components/loxone/api.py", line 77, in getJson
    api_resp = await requests.get(
  File "/usr/local/lib/python3.9/site-packages/requests_async/api.py", line 11, in get
    return await request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/api.py", line 6, in request
    return await session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_async/sessions.py", line 320, in __aexit__
    await self.close()
  File "/usr/local/lib/python3.9/site-packages/requests_async/sessions.py", line 311, in close
    await v.close()
  File "/usr/local/lib/python3.9/site-packages/requests_async/adapters.py", line 65, in close
    await self.pool.close()
**TypeError: object NoneType can't be used in 'await' expression**

**Comment by rosch99** [comment]
I had an older version of PyLoxone installed, after upgrading to the recent version the integration is working again.
Thanks and keep up the great work!
