### PR TITLE
Fix websocket service error on float call inside value

### PR DESCRIPTION
**Pull request by johny-mnemonic**
Strip function doesn't react well to float producing error: "AttributeError: 'float' object has no attribute 'strip'"

Unfortunately users can easily smuggle the float call into value for example as a part of template.

### CODE REVIEW

**Comment by JoDehli** [comment]
Can you check if it is still working.

**Comment by johny-mnemonic** [comment]
Sorry, I was busy with other stuff and got to it now.
After updating to 0.5.0b2 it seems to work fine. Thanks
