### ISSUE TITLE
Beta 0.5.0b1 websocket issues

### ISSUE THREAD

**Issue by johny-mnemonic** [JoDehli/PyLoxone#165]
Miniserver: Gen1
Loxone: 13.1.11.17
Hassio OS 9.5
HomeAssistant: 2023.2.5

I tried updating to beta 0.5.0b1 and after few hours I noticed I have no updates of values from HA in Loxone.
I am using websocket calls in automations to send for example energy consumption data from ESPHome energy meters/smart sockets.

The service call which works in PyLoxone 0.4.2:
```
action:
  - service: loxone.event_websocket_command
    data:
      uuid: 1a34e499-0352-cb47-ffffd7846630eb23
      value: "{{states.sensor.bw_zasuvka2_power.state | float(0) * 0.001 | float}}"
```
Produces following unhandled error in 0.5.0b1:
```
2023-02-20 23:50:00.806 ERROR (MainThread) [homeassistant.components.automation.loxone_set_rekuperace_power] Loxone - Set Rekuperace power: Error executing script. Unexpected error for call_service at pos 1: 'float' object has no attribute 'strip'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/loxone/__init__.py", line 335, in handle_websocket_command
value = value.strip()
AttributeError: 'float' object has no attribute 'strip'
2023-02-20 23:50:00.808 ERROR (MainThread) [homeassistant.components.automation.loxone_set_rekuperace_power] While executing automation automation.loxone_set_rekuperace_power
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 546, in async_trigger
await self.action_script.async_run(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/loxone/__init__.py", line 335, in handle_websocket_command
value = value.strip()
AttributeError: 'float' object has no attribute 'strip'
```

Before I realized it's failing due to PyLoxone update I tried modifying the automations as I thought it's templating issue.
This fails the same as original:
```
action:
  - service: loxone.event_websocket_command
    data_template:
      uuid: 1a34e499-0352-cb47-ffffd7846630eb23
      value: "{{states.sensor.bw_zasuvka2_power.state | float(0) * 0.001 | float}}"
```
And this one silently passes, but does not update the value in Loxone:
```
action:
  - service: loxone.event_websocket_command
    data:
      uuid: 1a34e499-0352-cb47-ffffd7846630eb23
      value_template: "{{states.sensor.bw_zasuvka2_power.state | float(0) * 0.001 | float}}"
```

I also tried restarting the Miniserver and double-checked the target virtual inputs are correctly set in Loxone, as I did lot of changes to energy monitoring this weekend.
This is how the beta version handled the Miniserver restart:
First it reported this:
```
Logger: homeassistant
Source: custom_components/loxone/pyloxone_api/connector.py:110
Integration: PyLoxone (documentation, issues)
First occurred: 23:24:10 (1 occurrences)
Last logged: 23:24:10

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/loxone/pyloxone_api/miniserver.py", line 384, in _do_restart
    await self.connect()
  File "/config/custom_components/loxone/pyloxone_api/miniserver.py", line 155, in connect
    await self._ensure_reachable()
  File "/config/custom_components/loxone/pyloxone_api/connector.py", line 110, in _ensure_reachable
    raise LoxoneException("Cannot connect. Are the host/port details correct?")
custom_components.loxone.pyloxone_api.exceptions.LoxoneException: Cannot connect. Are the host/port details correct?
```
And then the log was filled with errors from running automations:
```
2023-02-20 23:28:48.802 ERROR (MainThread) [homeassistant.components.automation.loxone_set_rekuperace_power] Loxone - Set Rekuperace power: Error executing script. Unexpected error for call_service at pos 1: Cannot write to closing transport
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/loxone/__init__.py", line 338, in handle_websocket_command
await miniserver.send_control_command(device_uuid, value)
File "/config/custom_components/loxone/pyloxone_api/miniserver.py", line 217, in send_control_command
return await self._send_text_command(cmd)
File "/config/custom_components/loxone/pyloxone_api/miniserver.py", line 319, in _send_text_command
await self._ws.send_str(command)
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_ws.py", line 151, in send_str
await self._writer.send(data, binary=False, compress=compress)
File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 690, in send
await self._send_frame(message, WSMsgType.TEXT, compress)
File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 601, in _send_frame
raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2023-02-20 23:28:48.804 ERROR (MainThread) [homeassistant.components.automation.loxone_set_rekuperace_power] While executing automation automation.loxone_set_rekuperace_power
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 546, in async_trigger
await self.action_script.async_run(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/loxone/__init__.py", line 338, in handle_websocket_command
await miniserver.send_control_command(device_uuid, value)
File "/config/custom_components/loxone/pyloxone_api/miniserver.py", line 217, in send_control_command
return await self._send_text_command(cmd)
File "/config/custom_components/loxone/pyloxone_api/miniserver.py", line 319, in _send_text_command
await self._ws.send_str(command)
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_ws.py", line 151, in send_str
await self._writer.send(data, binary=False, compress=compress)
File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 690, in send
await self._send_frame(message, WSMsgType.TEXT, compress)
File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 601, in _send_frame
raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```
Would it be possible in the future to have a sensor/attribute to check in the automation whether the Miniserver is accessible (i.e. not restarting), so it would block automations which are trying to send data to the Miniserver?

**Comment by JoDehli** [comment]
@johny-mnemonic Can you fix it and make a pull request?

**Comment by johny-mnemonic** [comment]
@JoDehli I can try, but I am total noob in Python;-)
I have found that the issue is that float can't be mixed with strip function.
For example this works:
`float(value.strip())`
But this fails with the error I am seeing:
`float(value).strip()`
What I don't understand is, why you changed the code [from](https://github.com/JoDehli/PyLoxone/blob/master/custom_components/loxone/__init__.py#L236)
`value = call.data.get(ATTR_VALUE, DEFAULT)`
[to](https://github.com/JoDehli/PyLoxone/blob/0.5.0b1/custom_components/loxone/__init__.py#L335)
`value.strip()`
It probably means that in this form my template `value: "{{xxx.state | float}}` ends up as `float(xxx.state).strip()` in final code which doesn't fly.
Would it be an issue to return back to the old `call.data.get` or simply drop that `strip()` function? Do we need it there?
It looks like a safety measure for bad user input and it would make sense on string-only field but as this `value` field can contain almost anything so that strip function is bringing more trouble than it solves IMO.

**Comment by johny-mnemonic** [comment]
@JoDehli I have updated back to 0.5.01b and tried to remove `strip()` on the value and it works without any errors:
https://github.com/JoDehli/PyLoxone/pull/166

**Comment by JoDehli** [comment]
fixed in new beta release
