### ISSUE TITLE
dns.loxonecloud.com adress not working on 0.3.9 

### ISSUE THREAD

**Issue by coreGreenberet** [JoDehli/PyLoxone#104]
```
Logger: homeassistant.config_entries
Source: custom_components/loxone/api.py:145
Integration: PyLoxone ([documentation](https://github.com/JoDehli/PyLoxone), [issues](https://github.com/JoDehli/PyLoxone/issues))
First occurred: 21:43:21 (1 occurrences)
Last logged: 21:43:21
Error setting up entry PyLoxone for loxone

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loxone/__init__.py", line 141, in async_setup_entry
    if not await miniserver.async_setup():
  File "/config/custom_components/loxone/miniserver.py", line 118, in async_setup
    request_code = await self.lox_config.getJson()
  File "/config/custom_components/loxone/api.py", line 145, in getJson
    verify=self._tls_check_hostname,
AttributeError: 'LoxApp' object has no attribute '_tls_check_hostname'
```

**Comment by JoDehli** [comment]
Refresh the 0.3.9 install via hacs and try again.

**Comment by coreGreenberet** [comment]
Now It's working, but I had another problem:
I had to change the the miniserver address from dns.loxonecloud.com/XXXXXXXXXXXX to it's ip 192.168.*.* address.
with the loxonecloud.com I got an 307 error from the cloud and the integration just handled it as an error

**Comment by JoDehli** [comment]
@coreGreenberet  Did it worked in the version before? 
Which gen do you have? Gen1 or Gen2?

**Comment by coreGreenberet** [comment]
yes it did work on the old version, just as described in the instuctions.
I have a Gen2

**Comment by JoDehli** [comment]
I try to fix it and maybe you can try it. It is not so easy as I have a gen1.

**Comment by JoDehli** [comment]
@coreGreenberet can you try the master branch with the external address? If it is still not working can you paste the error logs with this log settings: 
```yaml
logger:
  default: warning
  logs:
    homeassistant: warning
    homeassistant.helpers: warning
    custom_components.loxone: debug
    custom_components.loxone.api: debug
```

**Comment by JoDehli** [comment]
@coreGreenberet have you tried it with the master branch?

**Comment by coreGreenberet** [comment]
Sorry I wasn't at home this week, so I couldn't test it. I will try it tomorrow.

**Comment by AHub88** [comment]
@coreGreenberet 
Could you solve the problem?

**Comment by JoDehli** [comment]
@AHub88 no as I have no gen2. I can not solve this problem. Sorry you must use the local connection.

**Comment by JoDehli** [comment]
@AHub88 can you try the PyloxoneBeta? 

https://github.com/JoDehli/PyLoxone_beta

You can download the source an copy all files from the custom_components/loxone folder.

**Comment by coreGreenberet** [comment]
sorry got corona and completely forgot to test this.
I'm using directly the ip address at the moment and that is working for me.
