### ISSUE TITLE
[Bug]: Does not work after updating to HA Core 2025.7.4

### ISSUE THREAD

**Issue by dawon** [JoDehli/PyLoxone#412]
### Describe the bug

After updating HA Core to 2025.7.4 pyLoxone stopped working with following error in log...

I am suspecting a component of HA was updated with a breaking change?

### Firmware of your Miniserver

15.5.3.4

### HomeAssistant install method

manual install

### Version of HomeAssistant

2025.7.4

### Version of Pyloxone

0.8.1

### Update pyloxone

there was not a update

### Log

```
Logger: homeassistant.config_entries
Zdroj: config_entries.py:749
První výskyt: 07:01:41 (1 výskyt)
Naposledy logováno: 07:01:41

Error setting up entry PyLoxone for loxone
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/__init__.py", line 415, in async_setup_entry
    res = await miniserver.start_ws()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/miniserver.py", line 123, in start_ws
    res = await self.api.async_init()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loxone/api.py", line 497, in async_init
    message = await self._ws.recv(decode=False)
                    ~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: WebSocketCommonProtocol.recv() got an unexpected keyword argument 'decode'
```

**Comment by JoDehli** [comment]
@dawon it has nothing to do with the the newest Ha update. You have old web sockets lib installed. You can try to uninstall pyloxone. 
Remove pyloxone restart ha. They install it again. You can also use the newest beta release. Glad to get feedback for the new beta. 

If this does not work reinstall home assistant.

**Comment by dawon** [comment]
I did reinstall it (to prerelease) and it works now, thank you!
